{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mc-user-fastapi.fullname" . }}
  labels:
    {{- include "mc-user-fastapi.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mc-user-fastapi.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if or .Values.networkPolicy.allowSameNamespace (gt (len .Values.networkPolicy.ingressCIDRs) 0) }}
  ingress:
    - from:
        {{- if .Values.networkPolicy.allowSameNamespace }}
        - podSelector: {}
        {{- end }}
        {{- range .Values.networkPolicy.ingressCIDRs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
  {{- else }}
  ingress: []
  {{- end }}
  {{- if .Values.networkPolicy.egressAllowAll }}
  egress:
    - {}
  {{- else }}
  egress: []
  {{- end }}
{{- end }}
