apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc-user-fastapi.fullname" . }}
  labels:
    {{- include "mc-user-fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mc-user-fastapi.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
